# Generated by Django 4.1.1 on 2022-09-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
