# Generated by Django 4.1.1 on 2022-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='promotion')),
                ('description', models.CharField(max_length=250, verbose_name='promotion description')),
                ('url', models.CharField(max_length=120)),
            ],
        ),
    ]
