# Generated by Django 4.1.1 on 2022-10-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MakeMoneyBetting',
            new_name='affiliate',
        ),
    ]
